<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ProjectName>StopDropScattering</ProjectName>
		<AssemblyName>$(ProjectName)</AssemblyName>
		<RootNamespace>$(ProjectName)</RootNamespace>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
	</PropertyGroup>

	<PropertyGroup>
		<VersionMajor>0</VersionMajor>
		<VersionMinor>1</VersionMinor>
		<VersionPatch>1</VersionPatch>
		<VersionSuffix></VersionSuffix>
		<Authors>Yvonne Pautz</Authors>
		<Product>StopDropScattering</Product>
	</PropertyGroup>

	<PropertyGroup>
		<PluginFile>Plugin</PluginFile>
		<PluginGUID>Vonny1412.StopDropScattering</PluginGUID>
		<PluginName>$(Product)</PluginName>
		<PluginClass>Plugin</PluginClass>
	</PropertyGroup>

	<PropertyGroup>
		<CopyToPluginsSubDirectory>Vonny1412.StopDropScattering</CopyToPluginsSubDirectory>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Jotunn">
			<HintPath>..\.References\Jotunn.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Import Project="$(SolutionDir)\Valheim.Paths.props" />
	<Import Project="$(SolutionDir)\Valheim.Libraries.props" />
	<Import Project="$(SolutionDir)\Valheim.Mods.targets" />
	<ItemGroup>
	  <Compile Remove="publish\**" />
	  <EmbeddedResource Remove="publish\**" />
	  <None Remove="publish\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove=".publish.bat" />
	  <None Remove=".publish.ps1" />
	</ItemGroup>

</Project>